Sprint 3
tanianova/middle.messenger.praktikum.yandex pull request #4
Opened 2023-03-23 11:56 UTC by tanianova

2023-03-25 10:01 UTC, podlovchenko requested changes
Привет, в целом все здорово, хорошая работа 👍 Сейчас только при обновлении страницы локально запущенного проекта `Cannot GET /settings`, нужно исправить

2023-03-25 11:31 UTC, tanianova commented on src/api/AuthAPI.ts
> +  read(): Promise<User> {
добрый день, не могу воспроизвести ваше замечание , и соответственно отладить  "Сейчас только при обновлении страницы локально запущенного проекта Cannot GET /settings". Можно пожалуйста подробнее, как и где появляется ошибка?

2023-03-25 12:19 UTC, tanianova commented on src/components/avatar/index.ts
> +      avatar: `https://ya-praktikum.tech/api/v2/resources${props.avatar}`,
вынесено в константу

2023-03-25 12:20 UTC, tanianova commented on src/components/buttonDeleteChat/index.ts
> +import Block from "../../utils/Block";
спасибо, дефолтные экспорты заменены на обычные)

2023-03-25 15:21 UTC, tanianova commented on src/api/AuthAPI.ts
> +  read(): Promise<User> {
спасибо)

2023-03-26 11:59 UTC, podlovchenko commented
Спасибо за оперативные правки, работу принимаю)

2023-03-29 07:47 UTC, merged